on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front/my-page

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Generate coverage badge
        uses: jaywcjlove/coverage-badges-cli@main
        with:
          source: coverage/coverage-summary.json
          output: coverage/badge.svg

      - name: Commit badge to repo
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add coverage/badge.svg
          git commit -m "Update coverage badge"
          git push